DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Tunti CASCADE;
DROP TABLE IF EXISTS Laji CASCADE;
DROP TABLE IF EXISTS Varaus CASCADE;

/*
DROP TABLE IF EXISTS Game CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Player CASCADE;
*/